name: Build

on:
  push:
    branches:
        - master
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '1.13.0'
          secrets: |
            CASTLE_API_SECRET
            CASTLE_APP_ID
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CASTLE_API_SECRET: ${{ secrets.CASTLE_API_SECRET }}
          CASTLE_APP_ID: ${{ secrets.CASTLE_APP_ID }}
