name: Build

on:
  push:
    branches:
        - master
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            CASTLE_CLOUDFLARE_KEY
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CASTLE_CLOUDFLARE_KEY: ${{ secrets.CASTLE_CLOUDFLARE_KEY }}
